services:
  - type: web
    name: h1b-monitor
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: WA_PHONE
        sync: false
      - key: WA_APIKEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
