services:
  - type: web
    name: h1b-slot-watcher
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn monitor:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
